lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_SECRET)%"
  token_ttl: 3600 # 1 hora
  user_id_claim: sub
  token_extractors:
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization
